version: '2'
services:
  clasp-min-run:
    image: clasp-min-run
    build:
      context: .
      dockerfile: tools/dockerfiles/clasp-min-run/Dockerfile
    depends_on:
      - clasp-min-install
  clasp-min-install:
    image: clasp-min-install
    build:
      context: .
      dockerfile: tools/dockerfiles/clasp-min-install/Dockerfile
    depends_on:
      - clasp-dependencies
      - clasp-full-build
  clasp-full-build:
    image: clasp-full-build
    build:
      context: .
      dockerfile: tools/dockerfiles/clasp-full-build/Dockerfile
      args:
        CANDO_REVISION: dev
    volumes:
      - /tmp/install:/home/app/install
    command: bash -c 'cp -av /home/app/clasp/build/* /tmp/'
    depends_on:
      - clasp-dependencies
  clasp-externals:
    image: clasp-externals
    build:
      context: tools/dockerfiles/clasp-externals
      args:
        EXTERNALS_REVISION: master
    command: echo Done building clasp-externals.
  clasp-dependencies:
    image: clasp-dependencies
    build:
      context: tools/dockerfiles/clasp-dependencies
      args:
        EXTERNALS_REVISION: master
    command: echo Done building clasp-dependencies.
